### ISSUE TITLE
Call sign generation 

### ISSUE THREAD

**Issue by chrisleduc** [swiss-virtual/occ#4]
Keep a manual list of validated call signs. Do not generate fake call signs anymore. Just display SWR instead of LX.

**Comment by albertorestifo** [comment]
So you mean to display the callsign instead of the flight number?

And you do know that the flights are about 3-4k. What about the ones not on the manual list?

**Comment by chrisleduc** [comment]
The idea was to have a default of replacing LX with SWR in the call sign but to use the same number. And to keep a list with verified alphanumericals. 

The data from the list has priority and if not existing, it reverts the default.

**Comment by chrisleduc** [comment]
If at some point SWISS provides us with a list we can then integrate it. If they don't, we can slowly compile it. Johannes confirmed that he and Alexander would submit any necessary work hours needed to retrieve those over time.

**Comment by albertorestifo** [comment]
Just want to point out, the automatic callsign replacement was attempting to make more readable callsigns.

Tailing `0` are not really the best thing. And I'm not against the idea, just putting possible problems out there. 

> SWR1050
> SWR50
> EDW430

Those are all actual callsigns with the pattern `<SWR|EDW><FlightNumber>`

**Comment by albertorestifo** [comment]
Implemented with the import script
